version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mini_uber_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: ./server
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres=postgres@postgres:5432/miniuber_db
      - USE_POSTGRES=true
    depends_on:
      - postgres

  client:
    build: ./client
    ports:
      - "8001:8001"
    environment:
      - SERVER_URL=http://server:8000
    depends_on:
      - server

volumes:
  postgres_data: